// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package server

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ErrorCode.
const (
	BADREQUEST          ErrorCode = "BAD_REQUEST"
	FORBIDDEN           ErrorCode = "FORBIDDEN"
	INTERNALSERVERERROR ErrorCode = "INTERNAL_SERVER_ERROR"
	NOTFOUND            ErrorCode = "NOT_FOUND"
	TIMEOUT             ErrorCode = "TIMEOUT"
)

// CreateSubscriptionRequest defines model for CreateSubscriptionRequest.
type CreateSubscriptionRequest struct {
	Price       int                `json:"price"`
	ServiceName string             `json:"service_name"`
	StartDate   openapi_types.Date `json:"start_date"`
	UserId      openapi_types.UUID `json:"user_id"`
}

// ErrorCode Код ошибки для ответа
type ErrorCode string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Code Код ошибки для ответа
	Code    ErrorCode `json:"code"`
	Message string    `json:"message"`
}

// Subscription defines model for Subscription.
type Subscription struct {
	DeleteDate  *openapi_types.Date `json:"delete_date"`
	EndDate     *openapi_types.Date `json:"end_date"`
	Id          int                 `json:"id"`
	Price       int                 `json:"price"`
	ServiceName string              `json:"service_name"`
	StartDate   openapi_types.Date  `json:"start_date"`
	UserId      openapi_types.UUID  `json:"user_id"`
}

// SubscriptionId defines model for SubscriptionId.
type SubscriptionId struct {
	Id int `json:"id"`
}

// SubscriptionList defines model for SubscriptionList.
type SubscriptionList struct {
	Items *[]Subscription `json:"items,omitempty"`
}

// UpdateSubscriptionRequest defines model for UpdateSubscriptionRequest.
type UpdateSubscriptionRequest struct {
	EndDate *openapi_types.Date `json:"end_date"`
	Price   *int                `json:"price"`
}

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// InternalServerError defines model for InternalServerError.
type InternalServerError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// GetSubscriptionListParams defines parameters for GetSubscriptionList.
type GetSubscriptionListParams struct {
	UserId *openapi_types.UUID `form:"user_id,omitempty" json:"user_id,omitempty"`
	Limit  *int                `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int                `form:"offset,omitempty" json:"offset,omitempty"`
}

// CreateSubscriptionJSONRequestBody defines body for CreateSubscription for application/json ContentType.
type CreateSubscriptionJSONRequestBody = CreateSubscriptionRequest

// UpdateSubscriptionJSONRequestBody defines body for UpdateSubscription for application/json ContentType.
type UpdateSubscriptionJSONRequestBody = UpdateSubscriptionRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Получить список подписок
	// (GET /subscriptions)
	GetSubscriptionList(w http.ResponseWriter, r *http.Request, params GetSubscriptionListParams)
	// Создать подписку
	// (POST /subscriptions)
	CreateSubscription(w http.ResponseWriter, r *http.Request)
	// Отменить подписку
	// (DELETE /subscriptions/{id})
	CancelSubscription(w http.ResponseWriter, r *http.Request, id int)
	// Получить подписку по ID
	// (GET /subscriptions/{id})
	GetSubscription(w http.ResponseWriter, r *http.Request, id int)
	// Обновить подписку частично
	// (PATCH /subscriptions/{id})
	UpdateSubscription(w http.ResponseWriter, r *http.Request, id int)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Получить список подписок
// (GET /subscriptions)
func (_ Unimplemented) GetSubscriptionList(w http.ResponseWriter, r *http.Request, params GetSubscriptionListParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Создать подписку
// (POST /subscriptions)
func (_ Unimplemented) CreateSubscription(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Отменить подписку
// (DELETE /subscriptions/{id})
func (_ Unimplemented) CancelSubscription(w http.ResponseWriter, r *http.Request, id int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить подписку по ID
// (GET /subscriptions/{id})
func (_ Unimplemented) GetSubscription(w http.ResponseWriter, r *http.Request, id int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Обновить подписку частично
// (PATCH /subscriptions/{id})
func (_ Unimplemented) UpdateSubscription(w http.ResponseWriter, r *http.Request, id int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetSubscriptionList operation middleware
func (siw *ServerInterfaceWrapper) GetSubscriptionList(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSubscriptionListParams

	// ------------- Optional query parameter "user_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "user_id", r.URL.Query(), &params.UserId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_id", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSubscriptionList(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// CreateSubscription operation middleware
func (siw *ServerInterfaceWrapper) CreateSubscription(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSubscription(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// CancelSubscription operation middleware
func (siw *ServerInterfaceWrapper) CancelSubscription(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, chi.URLParam(r, "id"), &id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelSubscription(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetSubscription operation middleware
func (siw *ServerInterfaceWrapper) GetSubscription(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, chi.URLParam(r, "id"), &id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSubscription(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// UpdateSubscription operation middleware
func (siw *ServerInterfaceWrapper) UpdateSubscription(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, chi.URLParam(r, "id"), &id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateSubscription(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/subscriptions", wrapper.GetSubscriptionList)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/subscriptions", wrapper.CreateSubscription)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/subscriptions/{id}", wrapper.CancelSubscription)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/subscriptions/{id}", wrapper.GetSubscription)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/subscriptions/{id}", wrapper.UpdateSubscription)
	})

	return r
}

type BadRequestJSONResponse ErrorResponse

type InternalServerErrorJSONResponse ErrorResponse

type NotFoundJSONResponse ErrorResponse

type GetSubscriptionListRequestObject struct {
	Params GetSubscriptionListParams
}

type GetSubscriptionListResponseObject interface {
	VisitGetSubscriptionListResponse(w http.ResponseWriter) error
}

type GetSubscriptionList200JSONResponse SubscriptionList

func (response GetSubscriptionList200JSONResponse) VisitGetSubscriptionListResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetSubscriptionList400JSONResponse struct{ BadRequestJSONResponse }

func (response GetSubscriptionList400JSONResponse) VisitGetSubscriptionListResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetSubscriptionList500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetSubscriptionList500JSONResponse) VisitGetSubscriptionListResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateSubscriptionRequestObject struct {
	Body *CreateSubscriptionJSONRequestBody
}

type CreateSubscriptionResponseObject interface {
	VisitCreateSubscriptionResponse(w http.ResponseWriter) error
}

type CreateSubscription201JSONResponse SubscriptionId

func (response CreateSubscription201JSONResponse) VisitCreateSubscriptionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateSubscription400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateSubscription400JSONResponse) VisitCreateSubscriptionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateSubscription500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response CreateSubscription500JSONResponse) VisitCreateSubscriptionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CancelSubscriptionRequestObject struct {
	Id int `json:"id"`
}

type CancelSubscriptionResponseObject interface {
	VisitCancelSubscriptionResponse(w http.ResponseWriter) error
}

type CancelSubscription204Response struct {
}

func (response CancelSubscription204Response) VisitCancelSubscriptionResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type CancelSubscription404JSONResponse struct{ NotFoundJSONResponse }

func (response CancelSubscription404JSONResponse) VisitCancelSubscriptionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type CancelSubscription500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response CancelSubscription500JSONResponse) VisitCancelSubscriptionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetSubscriptionRequestObject struct {
	Id int `json:"id"`
}

type GetSubscriptionResponseObject interface {
	VisitGetSubscriptionResponse(w http.ResponseWriter) error
}

type GetSubscription200JSONResponse Subscription

func (response GetSubscription200JSONResponse) VisitGetSubscriptionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetSubscription400JSONResponse struct{ BadRequestJSONResponse }

func (response GetSubscription400JSONResponse) VisitGetSubscriptionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetSubscription404JSONResponse struct{ NotFoundJSONResponse }

func (response GetSubscription404JSONResponse) VisitGetSubscriptionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetSubscription500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetSubscription500JSONResponse) VisitGetSubscriptionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UpdateSubscriptionRequestObject struct {
	Id   int `json:"id"`
	Body *UpdateSubscriptionJSONRequestBody
}

type UpdateSubscriptionResponseObject interface {
	VisitUpdateSubscriptionResponse(w http.ResponseWriter) error
}

type UpdateSubscription200JSONResponse Subscription

func (response UpdateSubscription200JSONResponse) VisitUpdateSubscriptionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateSubscription404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateSubscription404JSONResponse) VisitUpdateSubscriptionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateSubscription500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response UpdateSubscription500JSONResponse) VisitUpdateSubscriptionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Получить список подписок
	// (GET /subscriptions)
	GetSubscriptionList(ctx context.Context, request GetSubscriptionListRequestObject) (GetSubscriptionListResponseObject, error)
	// Создать подписку
	// (POST /subscriptions)
	CreateSubscription(ctx context.Context, request CreateSubscriptionRequestObject) (CreateSubscriptionResponseObject, error)
	// Отменить подписку
	// (DELETE /subscriptions/{id})
	CancelSubscription(ctx context.Context, request CancelSubscriptionRequestObject) (CancelSubscriptionResponseObject, error)
	// Получить подписку по ID
	// (GET /subscriptions/{id})
	GetSubscription(ctx context.Context, request GetSubscriptionRequestObject) (GetSubscriptionResponseObject, error)
	// Обновить подписку частично
	// (PATCH /subscriptions/{id})
	UpdateSubscription(ctx context.Context, request UpdateSubscriptionRequestObject) (UpdateSubscriptionResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHttpHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHttpMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetSubscriptionList operation middleware
func (sh *strictHandler) GetSubscriptionList(w http.ResponseWriter, r *http.Request, params GetSubscriptionListParams) {
	var request GetSubscriptionListRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSubscriptionList(ctx, request.(GetSubscriptionListRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSubscriptionList")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSubscriptionListResponseObject); ok {
		if err := validResponse.VisitGetSubscriptionListResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateSubscription operation middleware
func (sh *strictHandler) CreateSubscription(w http.ResponseWriter, r *http.Request) {
	var request CreateSubscriptionRequestObject

	var body CreateSubscriptionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateSubscription(ctx, request.(CreateSubscriptionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateSubscription")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateSubscriptionResponseObject); ok {
		if err := validResponse.VisitCreateSubscriptionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CancelSubscription operation middleware
func (sh *strictHandler) CancelSubscription(w http.ResponseWriter, r *http.Request, id int) {
	var request CancelSubscriptionRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CancelSubscription(ctx, request.(CancelSubscriptionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CancelSubscription")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CancelSubscriptionResponseObject); ok {
		if err := validResponse.VisitCancelSubscriptionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSubscription operation middleware
func (sh *strictHandler) GetSubscription(w http.ResponseWriter, r *http.Request, id int) {
	var request GetSubscriptionRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSubscription(ctx, request.(GetSubscriptionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSubscription")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSubscriptionResponseObject); ok {
		if err := validResponse.VisitGetSubscriptionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateSubscription operation middleware
func (sh *strictHandler) UpdateSubscription(w http.ResponseWriter, r *http.Request, id int) {
	var request UpdateSubscriptionRequestObject

	request.Id = id

	var body UpdateSubscriptionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateSubscription(ctx, request.(UpdateSubscriptionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateSubscription")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateSubscriptionResponseObject); ok {
		if err := validResponse.VisitUpdateSubscriptionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RX307jxhd+lWh+v0trHbZUWvkOllBF2oZtgN6sUDTYJ+CV/zEeoyJkiYS2VNqVVupl",
	"pXa76gsYlogATXiFM29UzTgkduws2e0W2pvIGR+f+eY7n79zfEhM3w18DzweEuOQMAgD3wtB/VmmVhP2",
	"Igi5/Gf6HgdPXdIgcGyTctv39Jeh78m10NwFl8qr/zNoE4P8T5+k1tO7oV5jzGfN0SYkjmONWBCazA5k",
	"MmIQ/BV7eIVDcSSO5JXo4kC8wssKXmCCN+IIh6JDYo3UPQ7Mo846sH1gKu89ovwZB+JYdBXGAQ7EG/Gm",
	"gkPxE/bxFK8wqYgO9sQRnmFfdDCRgBs+X/Ujz7pHlL9jT3TEsTgSnQoOsCd/ErzEc4mayAdGueRWTxlQ",
	"DuvR9jhFpvgB8wNg3E6FETDbBHnBDwIgBrE9DjvA5ClDYPu2CS2PutmIkDPb21EBnDLesihXt9s+cykn",
	"BlELWjE8CoG1bCsXG0W2VYyNNcJgL7IZWMR4kQeijSBP8uWAbI2T+dsvweRyY8XuU99SMKd4/QWHeJ6t",
	"d7+C53idaqCLZ9gTXUyIRsCLXAlmo/51bW1zg2iksbbRWl3bbKwQjayuNZfrKyu1BtHI8tJKq1n7ZrO2",
	"LqPqjY1as7H0rLVea35ba7ZqzeZaMwNzwk9eBIVKmaMD3KkjddJYIy6EId0pK90UvyrzJL6MwqyWitAs",
	"cIDDTCV4kePQbQeIwVkEJScHz/r0h1NFFeX7X1B2qt6PkHeGq7vKVLeKhSrnqgjqrtzP7DIvsTm4+YsP",
	"aTUnqWkIKsEEBWWMHiigBVibgTWv1/0tmY3lNCMyy+YUSLlke22/aD9Lz+u3diOOVUtM8AyvVSfqSw9K",
	"8L1qTO8xET9iP3WnRPWpV+KHCg7xVP4M8Fp1g0EFb6Sh4Y1qVleYyCC5dC1e4wUO8QwT0cWe2uNS6tPm",
	"8ii56laWnteJRvaBhSnMhUfVR1VJgh+ARwObGOQLtaSRgPJdRa4eZjKolR1QNZAVoLeCJF8BLwhJZmHU",
	"BQ4sJMaLQ2LLTfciYAeyMuolzb4O45Z658tWnsqxXZvnElnQppHDifG4WlbQ8jR+ux3CjDxlaba0/Ez2",
	"uFr9bANEgdOyGeLdSBZDvMrrZIhXsrqLKaCyfcbA9cwkGWvky3keKZvv1MQSuS5lBxLaWyXRY3GCfdEV",
	"r+XM9WGsgR+WqKs4+JDUWCDky751MAff8B11A2dmpx3dDvXJViTW5qzS7LkszpuwdJa4IJeFf0QudatU",
	"LG/zPlJR1F+M3Cd5YLm8u8WixJL3PHGsovN+pB/aVjwZVUqUQz0TnIJycvwvlsyP0zSpqfFPZeC9CVGL",
	"d596/E3xGWn6bYylP4MobS6XJvfkXHMJMfvh88lCfLCSTBvddEnUQqW+ojwu3xWnePlDllUyonr76Mu6",
	"n/IiutgX36e3RVd+gk8PBn2ipU1NNvBJT1NtNO9DWXMr62kB5eZuUULFueyjrXg+Ac0eAOcy1YdU8hBP",
	"caCGsut/g1uM0cyQpjjBRHSUtk5kZHrIUGVMJRoxhxhkl/PA0HXHN6mz64fceFJ9UtVpYOv7CyTeiv8K",
	"AAD//36vtoaqEgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
